### ISSUE TITLE
sustain assumes component input will be named "model"

### ISSUE THREAD

**Issue by bgentry** [html-next/flexi#59]
I was invoking a component like so:

``` hbs
{{task-list model}}
```

That component was expecting the first argument to be called `tasks` and was using [`positionalParams`](https://guides.emberjs.com/v2.5.0/components/passing-properties-to-a-component/#toc_positional-params) so it could be provided as either the first argument or as `tasks=model`.

When I converted this component invocation to use `sustain`, I did this:

``` hbs
{{sustain "task-list" model}}
```

However this doesn't work because `sustain` always [assumes](https://github.com/runspired/flexi/blob/302ac7cd59437781f0db8e6e43d0b6c5fbd999fc/addon/lib/sustain.js#L232) that the input to the component will be called `model`. My component and its template were expecting the argument to be called `tasks` instead of `model`, so it wasn't rendering anything.

Perhaps the `sustain` helper should treat input [the same way as the `component` helper](https://github.com/emberjs/ember.js/blob/v2.5.0/packages/ember-htmlbars/lib/keywords/component.js#L12)?

**Comment by sheriffderek** [comment]
Can't you `{{sustain "task-list" model=somethingElse}}` ?

**Comment by bgentry** [comment]
@sheriffderek yes, but then my component needs to be altered to expect an input named `model` rather than `tasks`. IMO I should be able to invoke any component in exactly the same way whether it's used with `sustain` or not, and have it continue to work. But that's not the case today.

I'm making an attempt right now at a PR to solve this, we'll see how it goes :)

**Comment by sheriffderek** [comment]
@bgentry - Yes. Totally agree with that. I thought there might be an oversight.

**Comment by bgentry** [comment]
well this turned out to be quite a bit more complicated than I'd hoped for 😞. It looks like none of the logic that powers the `component` helper is reusable outside of Ember itself. I'll need somebody more knowledgeable than me to weigh in on whether I was correct about that being the right approach and how to go about implementing it.

To restate, what I want is for components that are invoked with `sustain` to require no changes other than switching i.e. `{{component-name input1 option1=true}}` to `{{sustain "component-name" input1 option1=true}}`. That means that the component's `positionalParams` and attrs continue to be passed along to the component in exactly the same way with no changes to my component required.

On a related note, the attrs used by the sustain component ([see here](https://github.com/runspired/flexi/blob/302ac7cd59437781f0db8e6e43d0b6c5fbd999fc/addon/lib/sustain.js#L17-L22)) have names that I could easily see colliding with users' real-world components. I wonder if it might also make sense to change these to something that is unlikely to be used by a user's component? Something like `flexiCopy` instead of `copy` or `flexiExpires` instead of `expires`.

**Comment by jasonmit** [comment]
Not knowing much about sustain (our project hasn't yet used it) but perhaps an API like the following would avoid naming conventions to avoid collisions:

```
{{sustain (component 'component-name' foo bar) expires=1000 copy=false}}
```

**Comment by runspired** [comment]
CC @machty 

I am interested in exploring this, but you are correct @bgentry that the `component` helper is absolutely not reusable outside of Ember atm.

We'd need to implement a custom keyword and largely reimplement the component helper.  My initial implementation of the sustain went down that path, and I realized I was entering into the waters of "often breaking private APIs".  There will be more breakage with glimmer2.  This is a situation I feel is bad for an addon, because there would be a big commitment to rework the sustain for multiple ember versions now and in the future.

RE Related note: this is precisely why I chose `model` and not `attrs`, and didn't try to make the sustain a magical proxy.

Meta Note: What you want is nice, but it does introduce other problems.  For one, `sustain` is NOT the `component` helper, and it's API is partially intentional to reflect that and enforce a clear choice to use it.

Second Meta Note: I've found that there's a sustain corollary which may be what you want, that I'm planning on building.

```
{{recycle-pool component-name input1 option1=true}}
```

```
{{#recycle-pool component-name input1 option1=true}}
...
{{/recycle-pool}}
```

**Comment by machty** [comment]
I'm still not following how/why the "component helper is absolutely not reusable outside of Ember atm."

Perhaps that's correct if you're trying to implement `sustain` the same way the top-level `{{component}}` is implemented (so that you could write `{{sustain componentName foo=bar wat=lol}}`, but what's the blocker on making `sustain` accept the value returned by the subexpression form of `(component 'x-foo' foo=bar)`? I'm still not following.

**Comment by runspired** [comment]
@machty was only referring to the former not the latter situation.

**Comment by machty** [comment]
Ah, well @bgentry I dunno if you're still interested but wanna take a stab at the `{{sustain (component ...)}}` approach?

**Comment by bgentry** [comment]
Happy to give it a try. Can you maybe elaborate on what that implementation
would look like?

My understanding is that there would be a `sustain` helper which would take
two required inputs. One would be the repeated name of the component (or
label) and the other would be the output of the component helper. AFAIK the
component name/label would have to be duplicated because the sustain helper
would have no other way of knowing what the component name or label was.
Then the helper would also take any optional attrs.

Any other hints you can offer to guide the way?

**Comment by machty** [comment]
@bgentry without digging super deep into it, this is what I saw when I placed a debugger in an action that was passed a reference to the value returned from `(component 'exc-app-header-button-x')`:

![image](https://cloud.githubusercontent.com/assets/81818/15635939/f1941b30-25bc-11e6-865d-1e8c25f5f20f.png)

I don't know how far you can take it before hitting a wall but it seems like you should be able to extract the same values out of that that you currently have to explicitly pass into `sustain`

**Comment by bgentry** [comment]
@machty I played around with this a bit. Using some pretty hacky methods to extract info from the closure component object shown in your screenshot. What I have in [this branch](https://github.com/runspired/flexi/compare/master...bgentry:sustain-arbitrary-input?expand=1) sort of works for simple inputs to the component, but not for more complicated inputs like the route `model`.

Those inputs are provided as [closure component stream](https://github.com/emberjs/ember.js/blob/beta/packages/ember-htmlbars/lib/keywords/closure-component.js#L23-L35) objects, the actual value of which is available by calling `.cache` or `.value()`:

<img width="957" alt="screen shot 2016-05-31 at 7 36 07 pm" src="https://cloud.githubusercontent.com/assets/114033/15696623/f83845aa-2766-11e6-8e6c-29a72cb7dede.png">

Is this the approach you were thinking of? Any idea how to proceed from here? I'm in way over my head here so any help is appreciated!

**Comment by runspired** [comment]
@bgentry I tried to spike this tonight, forgetting that you'd already done so, and hit similar walls. I'd like to take a peek at your branch again and see if we can't come to some resolution.

I suspect we need @chancancode to weigh in here.

**Comment by runspired** [comment]
Also to reiterate for people's benefits, ideally we could make `sustain` have the following API:

```hbs
{{sustain (component "foo" someAnon foo="bar") label="<a-value>" expires="0"}}
```

However, the wall seems to be that the component helper is a walled garden that is difficult (and likely unstable) to reach into.  Flexi needs a way to instantiate a component passed to it by the component helper with control over it's lifecycle in order to be able to function correctly.

**Comment by bgentry** [comment]
Glimmer 2 is merged. Does that make this feature more feasible?

**Comment by rwwagner90** [comment]
@bgentry glimmer 2 actually breaks sustain entirely. @runspired will the refactor of sustain to make it work with glimmer 2 be able to accomplish this as well?

**Comment by runspired** [comment]
No. This is something that sadly we will likely never be able to support because the `component` helper is the walled garden that it is.

**Comment by rwwagner90** [comment]
Since the man himself says this is unlikely to happy, I am going to close the issue. Feel free to open a PR if you happen to magically make something work @bgentry 😄

**Comment by bgentry** [comment]
@rwwagner90 hah, don't count on that :) Sounds like this would need some pretty serious help from the framework builders to properly expose the component helper.
